version: '3.8'

services:
  backend:
    build:
      context: ./TodoBackend
    ports:
      - "5260:80"
    volumes:
      - UploadsFolder:/app/UploadedPhotos

  frontend:
    build:
      context: ./TodoFrontend
    ports:
      - "4200:4200"

volumes:
  UploadsFolder:
